import Head from "next/head";
import Image from "next/image";
import logo from "/public/GREACHY.png";
import styles from "@component/styles/Home.module.css";

import Chatbot from "@component/componets/chatbot";

export default function Home() {
  return (
    <>
      <Head>
        <title>GreachyBot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <header className={styles.pageHeader}>
          <h1 className={styles.logo}>
            <Image
              src={logo}
              alt="Picture of robot waving with the word Greachy Bot below"
              width={200}
              height={200}
            />
          </h1>
        </header>
        <main className={styles.pageMain}>
          <div className={styles.element}>
            <Chatbot/>
          </div>
        </main>
        <footer className={styles.pageFooter}>
          <p>Greachy 2023</p>
        </footer>
      </div>
    </>
  );
}
